#!/usr/bin/env bun
/**
 * Generate src/lists.generated.ts: a module that statically imports every
 * data/<name>.json so `bun build --compile` embeds the bundled lists into the
 * standalone binary (which otherwise can't read files from disk / $bunfs).
 *
 * Run after changing data/ (or via `bun run build:data`). The output is
 * committed so both the compiled binary and from-source runs share one source
 * of truth.
 */
import { readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const DATA_DIR = join(ROOT, "data");
const OUT = join(ROOT, "src", "lists.generated.ts");

const names = (await readdir(DATA_DIR))
  .filter((f) => f.endsWith(".json"))
  .map((f) => f.replace(/\.json$/, ""))
  .sort();

// A safe JS identifier per list name (for the import binding).
const ident = (name: string): string => "l_" + name.replace(/[^a-zA-Z0-9]/g, "_");

const lines = [
  "// AUTO-GENERATED by scripts/gen-embed.ts — do not edit by hand.",
  "// Statically imports every bundled list so `bun build --compile` embeds them.",
  'import type { ProblemList } from "./types.ts";',
  "",
  ...names.map((n) => `import ${ident(n)} from "../data/${n}.json" with { type: "json" };`),
  "",
  "/** Every bundled list, keyed by machine name; embedded in the compiled binary. */",
  "export const EMBEDDED_LISTS: Record<string, ProblemList> = {",
  ...names.map((n) => `  ${JSON.stringify(n)}: ${ident(n)} as ProblemList,`),
  "};",
  "",
];

await Bun.write(OUT, lines.join("\n"));
console.log(`wrote ${OUT} with ${names.length} lists`);
