#!/usr/bin/env bun
/**
 * Generate the Homebrew formula for a released version by reading the release
 * assets' SHA-256 checksums from GitHub. Print it to stdout; copy the result
 * into your tap repo (homebrew-leet/Formula/leet.rb).
 *
 *   bun run scripts/gen-formula.ts v0.2.0 > leet.rb
 *
 * Requires the release (with leet-<platform>-<arch>.sha256 assets) to exist.
 */
const OWNER = "DIvkov575";
const CLI_REPO = "leet-cli";

const tag = process.argv[2];
if (!tag) {
  console.error("usage: bun run scripts/gen-formula.ts <tag>   (e.g. v0.2.0)");
  process.exit(1);
}

const ASSETS = [
  { key: "darwin-arm64", asset: "leet-darwin-arm64" },
  { key: "darwin-x64", asset: "leet-darwin-x64" },
  { key: "linux-x64", asset: "leet-linux-x64" },
  { key: "linux-arm64", asset: "leet-linux-arm64" },
] as const;

const base = `https://github.com/${OWNER}/${CLI_REPO}/releases/download/${tag}`;

/**
 * Read the checksum for an asset via the GitHub API (`gh release download`).
 * The API path is authoritative immediately after upload, whereas the public
 * releases/download CDN URL can lag several minutes.
 */
async function sha(asset: string): Promise<string> {
  const proc = Bun.spawn(
    ["gh", "release", "download", tag, "--repo", `${OWNER}/${CLI_REPO}`, "--pattern", `${asset}.sha256`, "--output", "-"],
    { stdout: "pipe", stderr: "pipe" },
  );
  const [text, err, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  if (code !== 0) throw new Error(`no ${asset}.sha256 for ${tag}: ${err.trim()} — is the release built?`);
  const hex = text.trim().split(/\s+/)[0];
  if (!hex || !/^[0-9a-f]{64}$/.test(hex)) throw new Error(`bad checksum for ${asset}: ${text}`);
  return hex;
}

const sums = Object.fromEntries(
  await Promise.all(ASSETS.map(async (a) => [a.key, await sha(a.asset)] as const)),
);

const version = tag.replace(/^v/, "");
const rb = `# typed: false
# frozen_string_literal: true

# Homebrew formula for leet-cli. Generated by scripts/gen-formula.ts.
class Leet < Formula
  desc "Browse bundled LeetCode company problem lists from the terminal"
  homepage "https://github.com/${OWNER}/${CLI_REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${base}/leet-darwin-arm64"
      sha256 "${sums["darwin-arm64"]}"
    else
      url "${base}/leet-darwin-x64"
      sha256 "${sums["darwin-x64"]}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${base}/leet-linux-arm64"
      sha256 "${sums["linux-arm64"]}"
    else
      url "${base}/leet-linux-x64"
      sha256 "${sums["linux-x64"]}"
    end
  end

  def install
    bin.install stable.url.split("/").last => "leet"
  end

  def caveats
    <<~EOS
      Bundled problem lists are embedded, so browsing works offline immediately.
      Problem statements/stubs are cached lazily on first solve/preview.
      On first launch, leet offers to pre-cache the NeetCode 250 set (opt-in);
      or run it any time:  leet setup
      Suppress the suggestion with:  export LEET_NO_SETUP=1
    EOS
  end

  test do
    assert_match "neetcode-250", shell_output("#{bin}/leet lists")
  end
end
`;

console.log(rb);
