/**
 * Compiled-in offline artifacts: every bundled problem's packaged `.cpp`
 * (statement + stub + harness) and plain-text `desc` (statement body), keyed by
 * slug. Generated by `scripts/build-artifacts.ts` into artifacts/bundle.json and
 * statically imported here so `bun build --compile` embeds it in the standalone
 * binary — which is what lets a freshly installed `leet` preview, solve, and
 * test every bundled problem with zero network access.
 *
 * The cache (`cache.ts`) reads these as the offline fallback after the on-disk
 * user cache; see `getCached` / `getCachedDescription`.
 */
import bundle from "../artifacts/bundle.json" with { type: "json" };

export interface Artifact {
  /** Packaged editable C++ file (statement embedded, stub, test harness). */
  cpp?: string;
  /** Plain-text problem statement body (as shown in the preview). */
  desc?: string;
}

/** The embedded artifact bundle, slug → { cpp, desc }. */
export const EMBEDDED_ARTIFACTS: Record<string, Artifact> = bundle as Record<string, Artifact>;

/** The packaged `.cpp` for a slug from the embedded bundle, or null. */
export function embeddedCpp(slug: string): string | null {
  return EMBEDDED_ARTIFACTS[slug]?.cpp ?? null;
}

/** The plain-text statement for a slug from the embedded bundle, or null. */
export function embeddedDescription(slug: string): string | null {
  return EMBEDDED_ARTIFACTS[slug]?.desc ?? null;
}
