// AUTO-GENERATED by scripts/gen-embed.ts — do not edit by hand.
// Statically imports every bundled list so `bun build --compile` embeds them.
import type { ProblemList } from "./types.ts";

import l_bloomberg from "../data/bloomberg.json" with { type: "json" };
import l_bytedance from "../data/bytedance.json" with { type: "json" };
import l_citadel from "../data/citadel.json" with { type: "json" };
import l_de_shaw from "../data/de-shaw.json" with { type: "json" };
import l_google from "../data/google.json" with { type: "json" };
import l_hudson_river_trading from "../data/hudson-river-trading.json" with { type: "json" };
import l_jane_street from "../data/jane-street.json" with { type: "json" };
import l_jump_trading from "../data/jump-trading.json" with { type: "json" };
import l_meta from "../data/meta.json" with { type: "json" };
import l_neetcode_250 from "../data/neetcode-250.json" with { type: "json" };
import l_nvidia from "../data/nvidia.json" with { type: "json" };
import l_openai from "../data/openai.json" with { type: "json" };
import l_optiver from "../data/optiver.json" with { type: "json" };
import l_point72 from "../data/point72.json" with { type: "json" };
import l_sig from "../data/sig.json" with { type: "json" };
import l_two_sigma from "../data/two-sigma.json" with { type: "json" };
import l_uber from "../data/uber.json" with { type: "json" };
import l_virtu_financial from "../data/virtu-financial.json" with { type: "json" };
import l_waymo from "../data/waymo.json" with { type: "json" };

/** Every bundled list, keyed by machine name; embedded in the compiled binary. */
export const EMBEDDED_LISTS: Record<string, ProblemList> = {
  "bloomberg": l_bloomberg as ProblemList,
  "bytedance": l_bytedance as ProblemList,
  "citadel": l_citadel as ProblemList,
  "de-shaw": l_de_shaw as ProblemList,
  "google": l_google as ProblemList,
  "hudson-river-trading": l_hudson_river_trading as ProblemList,
  "jane-street": l_jane_street as ProblemList,
  "jump-trading": l_jump_trading as ProblemList,
  "meta": l_meta as ProblemList,
  "neetcode-250": l_neetcode_250 as ProblemList,
  "nvidia": l_nvidia as ProblemList,
  "openai": l_openai as ProblemList,
  "optiver": l_optiver as ProblemList,
  "point72": l_point72 as ProblemList,
  "sig": l_sig as ProblemList,
  "two-sigma": l_two_sigma as ProblemList,
  "uber": l_uber as ProblemList,
  "virtu-financial": l_virtu_financial as ProblemList,
  "waymo": l_waymo as ProblemList,
};
